// Funds from Paul's digest list of 11 Sept 2026 that the catalogue did not hold.
// Every page below was fetched in this session by direct fetch; deadlines marked
// (digest) were not readable on the page and come from Paul's list.
//   npx tsx --env-file=.env.local <file> [--apply]
import { getAdminDb } from '../src/lib/admin/admin-db'
import { stampNewGrant } from '../src/lib/grant-merge'
const APPLY = process.argv.includes('--apply'); const SRC = 'system:digest-2026-09-11'; const TODAY = '2026-09-11'
const NCF = 'Northamptonshire Community Foundation'
const ORGS = ['registered_charity', 'cio', 'cic_guarantee', 'cic_shares', 'ltd_guarantee', 'unincorporated', 'cooperative']
const b = (u: string, x: Record<string, unknown>) => ({ source: 'live_fetch', last_enriched: TODAY, open_status: 'open', ...x, _source_url: u })
const c = (snippet: string, source_url: string) => ({ snippet, confidence: 'high', source_url })
type Row = Record<string, unknown> & { title: string; funder: string; apply_url: string }
const NEW: Row[] = [
  { title: 'Margaret Giffen Community Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/margaret-giffen-fund', location_tag: 'North Northamptonshire', is_local: true, amount_min: null, amount_max: 3000, deadline: '2026-10-02', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['community', 'food', 'disability'], target_beneficiaries: ['disadvantaged'],
    description: 'Grants of up to £3,000 from the Northamptonshire Community Foundation to help local charities and community groups tackle poverty and disadvantage in North Northamptonshire, including Corby and Kettering. Projects must address at least one issue from the foundation\'s Hidden Needs report, such as food poverty, advice services, or activities for people with disabilities. Capital and running costs both eligible, with a total project budget under £20,000. Closes 2 October 2026.',
    funder_brief: b('https://www.ncf.uk.com/margaret-giffen-fund', { who_can_apply: 'Local charities and constituted community groups in North Northamptonshire.', what_they_fund: 'Projects tackling disadvantage and poverty that address a Hidden Needs report priority; revenue and capital.', typical_award: 'Up to £3,000.', decision_timeline: 'Closes Friday 2 October 2026.', how_to_apply: 'Online application from the fund page.', _citations: { typical_award: c('The Margaret Giffen Community Fund supports projects up to £3000 tackling disadvantage and poverty across Corby, Kettering and North Northamptonshire.', 'https://www.ncf.uk.com/margaret-giffen-fund'), decision_timeline: c('Margaret Giffen Community Fund Friday 2nd October 2026', 'https://www.ncf.uk.com/grants/grant-deadlines') } }) },
  { title: 'The Compton Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/the-compton-fund', location_tag: 'Northamptonshire', is_local: true, amount_min: 500, amount_max: 5000, deadline: '2026-10-02', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['creative', 'heritage', 'community'], target_beneficiaries: ['general_public'],
    description: 'Grants of £500 to £5,000 from the Northamptonshire Community Foundation for arts, culture and heritage projects across Northamptonshire. Local charities, community groups and social enterprises can use the money for core overheads, equipment or direct project costs, from sharing local history to musical performances and cultural celebrations. Closes 2 October 2026.',
    funder_brief: b('https://www.ncf.uk.com/the-compton-fund', { who_can_apply: 'Local charities, community groups and social enterprises in Northamptonshire.', what_they_fund: 'Arts, culture and heritage based projects; core overheads, equipment or project costs.', typical_award: '£500 to £5,000.', decision_timeline: 'Closes Friday 2 October 2026.', how_to_apply: 'Online application from the fund page.', _citations: { typical_award: c('The fund will offer awards between £500 and £5000 .', 'https://www.ncf.uk.com/the-compton-fund'), decision_timeline: c('The Compton Fund Friday 2nd October 2026', 'https://www.ncf.uk.com/grants/grant-deadlines') } }) },
  { title: 'Northamptonshire Queen\'s Institute Relief Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/queens-institute-fund', location_tag: 'Northamptonshire', is_local: true, amount_min: null, amount_max: 5000, deadline: '2026-10-02', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['health', 'mental_health', 'disability'], target_beneficiaries: ['general_public'],
    description: 'One-off grants of up to £5,000 from the Northamptonshire Community Foundation for projects that improve health and wellbeing across Northamptonshire: helping people manage health conditions, promoting active lifestyles, skills training for people with learning disabilities, and activities that reduce loneliness. Open to local charities and community interest companies. Closes 2 October 2026.',
    funder_brief: b('https://www.ncf.uk.com/queens-institute-fund', { who_can_apply: 'Local charities, constituted groups and CICs in Northamptonshire.', what_they_fund: 'Health and wellbeing projects for up to one year.', typical_award: 'Up to £5,000, one-off.', exclusions: 'Activities of a political nature; activities which exclusively support or promote religion.', decision_timeline: 'Closes Friday 2 October 2026.', how_to_apply: 'Online application from the fund page.', _citations: { typical_award: c('The Northamptonshire Queens Institute Fund will offer one-off grants up to £5000 for projects based in Northamptonshire that are all about improving health and wellbeing.', 'https://www.ncf.uk.com/queens-institute-fund'), decision_timeline: c('Northamptonshire Queen\'s Institute Fund Friday 2nd October 2026', 'https://www.ncf.uk.com/grants/grant-deadlines') } }) },
  { title: 'The Alastair James Memorial Trust', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/alastair-james-memorial-trust', location_tag: 'East Midlands and East of England', is_local: true, amount_min: null, amount_max: 1000, deadline: '2026-10-12', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['community'], target_beneficiaries: ['general_public'], applicant_type: 'both',
    description: 'Grants of up to £1,000 for registered charities and community or voluntary groups across the East Midlands and East Anglia with an annual income of £1.5 million or less, managed by the Northamptonshire Community Foundation. Funds projects or the purchase of equipment, with a preference for UK-made equipment. Individuals may also be supported at the trustees\' discretion. Closes midday 12 October 2026.',
    funder_brief: b('https://www.ncf.uk.com/alastair-james-memorial-trust', { who_can_apply: 'Registered charities and community or voluntary groups in the East Midlands and East Anglia with income of £1.5 million or less; individuals at the trustees\' discretion.', what_they_fund: 'Projects and equipment purchases.', typical_award: 'Up to £1,000 for groups.', decision_timeline: 'Closes Monday 12 October 2026 at midday.', how_to_apply: 'Online application from the fund page.', _citations: { typical_award: c('Groups can apply for up to £1,000 for their project.', 'https://www.ncf.uk.com/alastair-james-memorial-trust'), who_can_apply: c('Make grants to other registered charities and to community/voluntary groups throughout East Midlands and East Anglia.', 'https://www.ncf.uk.com/alastair-james-memorial-trust'), decision_timeline: c('Alastair James Memorial Trust Fund Monday 12th October at Midday 2026', 'https://www.ncf.uk.com/grants/grant-deadlines') } }) },
  { title: 'Amplius Community Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/grants/grants-available/amplius-community-fund', location_tag: 'Northamptonshire', is_local: true, amount_min: null, amount_max: 5000, deadline: '2026-10-14', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['health', 'financial', 'employment', 'community'], target_beneficiaries: ['disadvantaged'],
    description: 'Grants of up to £5,000 from the Amplius Community Fund, managed by the Northamptonshire Community Foundation, for local charities, community groups and social enterprises in areas where Amplius housing customers live. Supports projects that improve physical and mental health, give financial advice to people on a low income, or help residents into work. Core costs, capital equipment and project costs are all eligible. Closes 14 October 2026.',
    funder_brief: b('https://www.ncf.uk.com/grants/grants-available/amplius-community-fund', { who_can_apply: 'Local community organisations and social enterprises in Northamptonshire, aligned to Amplius\' Purposeful Impact work.', what_they_fund: 'Health and wellbeing, financial wellbeing and security, and employment support; can be used towards capital items.', typical_award: 'Up to £5,000 (digest figure; the page states no maximum in the text read).', exclusions: 'Social enterprises with a single person with significant control.', decision_timeline: 'Closes Wednesday 14 October 2026.', how_to_apply: 'Online application from the fund page.', _citations: { what_they_fund: c('Financial wellbeing and security - provision of advice and support to families and individuals on a low income, addressing fuel poverty, and reducing financial stress.', 'https://www.ncf.uk.com/grants/grants-available/amplius-community-fund'), decision_timeline: c('Amplius Community Fund Wednesday 14th October 2026', 'https://www.ncf.uk.com/grants/grant-deadlines') } }) },
  { title: 'Cecil Pettit Legacy Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/cecil-pettit-legacy-fund', location_tag: 'Northamptonshire', is_local: true, amount_min: null, amount_max: 3000, deadline: null, is_rolling: true, eligible_structures: ORGS, impact_sectors: ['disability', 'health'], target_beneficiaries: ['disabled'],
    description: 'Grants of up to £3,000 from the Cecil Pettit Legacy Fund, managed by the Northamptonshire Community Foundation, for local charities and community groups improving the lives of people with disabilities across Northamptonshire: advocacy, skills training, and health and wellbeing activities that reduce isolation. Project and capital costs for up to one year. Rolling, no deadline.',
    funder_brief: b('https://www.ncf.uk.com/cecil-pettit-legacy-fund', { who_can_apply: 'Local community organisations and social enterprises in Northamptonshire.', what_they_fund: 'Advocacy, skills or training, and health and wellbeing projects for people with disabilities.', typical_award: 'Up to £3,000.', exclusions: 'Social enterprises with a single person with significant control.', decision_timeline: 'Rolling; apply at any time.', how_to_apply: 'Cecil Pettit application form linked from the fund page.', _citations: { typical_award: c('The maximum funding award is £3,000.', 'https://www.ncf.uk.com/cecil-pettit-legacy-fund'), decision_timeline: c('We accept applications for our rolling programmes at any time , as there are no fixed deadlines .', 'https://www.ncf.uk.com/cecil-pettit-legacy-fund') } }) },
  { title: 'African & Caribbean Elders Service Legacy Fund', funder: NCF, funding_type: 'grant', apply_url: 'https://www.ncf.uk.com/grants/grants-available/african-and-caribbean-elders-service-legacy-fund', location_tag: 'Northamptonshire', is_local: true, amount_min: null, amount_max: 3000, deadline: null, is_rolling: true, eligible_structures: ORGS, impact_sectors: ['older_people', 'health', 'community'], target_beneficiaries: ['older_people', 'bame'],
    description: 'Grants of up to £3,000 for Black and Global Majority-led organisations supporting older people in Northamptonshire, managed by the Northamptonshire Community Foundation. Core, capital or project costs for activities that improve health, reduce isolation or offer home support. Rolling, with twelve months to spend the award.',
    funder_brief: b('https://www.ncf.uk.com/grants/grants-available/african-and-caribbean-elders-service-legacy-fund', { who_can_apply: 'Black and Global Majority-led charities, constituted community groups, CICs, or companies limited by guarantee with charitable aims, supporting older people in Northamptonshire.', what_they_fund: 'Health, isolation and home support activities for older people; core, capital or project costs.', typical_award: 'Up to £3,000.', decision_timeline: 'Rolling; apply at any time.', how_to_apply: 'Online application from the fund page.', _citations: { who_can_apply: c('such as a charity, constituted community group, social enterprise such as a Community Interest Company (CIC), or a company limited by guarantee with charitable aims.', 'https://www.ncf.uk.com/grants/grants-available/african-and-caribbean-elders-service-legacy-fund'), decision_timeline: c('We accept applications for our rolling programmes at any time , as there are no fixed deadlines .', 'https://www.ncf.uk.com/grants/grants-available/african-and-caribbean-elders-service-legacy-fund') } }) },
  { title: 'Luton Innovation & Collaboration Fund', funder: 'Bedfordshire and Luton Community Foundation', funding_type: 'grant', apply_url: 'https://blcf.org.uk/apply-for-a-grant/luton/luton-innovation-collaboration-fund/', location_tag: 'Luton', is_local: true, amount_min: 5000, amount_max: 30000, deadline: '2026-10-05', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['employment', 'education', 'young_people'], target_beneficiaries: ['unemployed', 'young_people'],
    description: 'Grants of £5,000 to £30,000 from the Bedfordshire and Luton Community Foundation for local charities and community groups running work and skills projects in Luton. This round backs new partnerships trying different ways to help residents overcome barriers to employment and training, with priority for collaborative ten-month projects supporting young people, people in long-term unemployment, and those facing challenges finding work. Total pot £110,000. Full applications close midday 5 October 2026.',
    funder_brief: b('https://blcf.org.uk/apply-for-a-grant/luton/luton-innovation-collaboration-fund/', { who_can_apply: 'Charities and community groups working in Luton, preferably in partnership.', what_they_fund: 'Work and skills projects that help residents overcome barriers to employment and training.', typical_award: '£5,000 to £30,000 from a £110,000 pot.', decision_timeline: 'Full applications close Monday 5 October 2026 at midday. The digest listed 2 October; the page says 5 October.', how_to_apply: 'Online application from the fund page.', _citations: { typical_award: c('Level of awards available is as follows: Awards from £5,000 up to £30,000 .', 'https://blcf.org.uk/apply-for-a-grant/luton/luton-innovation-collaboration-fund/'), decision_timeline: c('Deadline for full applications is Monday 5 th October at midday.', 'https://blcf.org.uk/apply-for-a-grant/luton/luton-innovation-collaboration-fund/'), open_status: c('This fund is now open.', 'https://blcf.org.uk/apply-for-a-grant/luton/luton-innovation-collaboration-fund/') } }) },
  { title: 'Common Ground Award 2026 to 2027', funder: 'Ministry of Housing, Communities and Local Government', funding_type: 'grant', apply_url: 'https://www.gov.uk/government/publications/common-ground-award-2026-to-2027-prospectus', location_tag: 'England', is_local: true, amount_min: 20000, amount_max: 250000, deadline: '2026-10-12', is_rolling: false, eligible_structures: ['registered_charity', 'cio', 'cic_guarantee', 'cic_shares', 'ltd_guarantee', 'cooperative'], impact_sectors: ['community'], target_beneficiaries: ['general_public'],
    description: 'Capital grants from the Ministry of Housing, Communities and Local Government for voluntary, community and social enterprise organisations in England to improve physical spaces and equipment that bring people from different backgrounds together. Individual organisations can apply for £20,000 to £50,000; consortiums for £100,000 to £250,000. Applicants must have income below £5 million and be based and operating in England. £2.5 million available in 2026 to 2027. Closing date 12 October 2026 per the funding digest; confirm on the prospectus.',
    funder_brief: b('https://www.gov.uk/government/publications/common-ground-award-2026-to-2027-prospectus', { who_can_apply: 'VCSE organisations based and operating in England with charitable, benevolent or philanthropic purposes and income below £5 million; one application per organisation, individually or in a consortium.', what_they_fund: 'Capital: building renovations, new builds or essential equipment that bring people from different backgrounds together.', typical_award: '£20,000 to £50,000 for an organisation; £100,000 to £250,000 for a consortium.', decision_timeline: 'Closes 12 October 2026 (digest; not confirmed in the page text read). Awards made as soon as possible after the application window.', how_to_apply: 'Through the prospectus and application form on GOV.UK.', _citations: { who_can_apply: c('Who can apply The grant is open to applications from VCSE organisations based and operating in England, with charitable, benevolent or philanthropic purposes.', 'https://www.gov.uk/government/publications/common-ground-award-2026-to-2027-prospectus/common-ground-award-2026-to-2027-prospectus'), typical_award: c('Individual applicants can apply for a grant between £20,000 and £50,000.', 'https://www.gov.uk/government/publications/common-ground-award-2026-to-2027-prospectus/common-ground-award-2026-to-2027-prospectus') }, _walk_note: 'Deadline is from the digest, not read on the page. Check before publishing.' }) },
  { title: 'Essential Employment Skills Fund', funder: 'Nuffield Foundation', funding_type: 'grant', apply_url: 'https://www.nuffieldfoundation.org/funding-for-research/essential-employment-skills-fund', location_tag: 'UK', is_local: false, amount_min: 200000, amount_max: 500000, deadline: '2026-12-10', is_rolling: false, eligible_structures: ['registered_charity', 'cio', 'cic_guarantee', 'ltd_guarantee'], impact_sectors: ['employment', 'young_people', 'education'], target_beneficiaries: ['young_people'],
    description: 'Grants of up to £500,000, most between £200,000 and £400,000, from the Nuffield Foundation to evaluate UK frontline programmes that help young people aged 16 to 24 facing significant barriers to work develop essential employment skills such as teamwork, communication and problem-solving. Applications are expected from a collaboration between an evaluator and a delivery organisation. Closes 10 December 2026.',
    funder_brief: b('https://www.nuffieldfoundation.org/funding-for-research/essential-employment-skills-fund', { who_can_apply: 'Collaborations between an evaluator and a delivery organisation; eligibility per Section 3 of the Nuffield Guide for Applicants.', what_they_fund: 'Evaluation of frontline programmes building essential employment skills for young people aged 16 to 24 facing barriers to work.', typical_award: 'Up to £500,000; most £200,000 to £400,000.', decision_timeline: 'Closes 10 December 2026 (digest).', how_to_apply: 'Through the Nuffield Foundation application portal.', _citations: { typical_award: c('We are offering grants of up to £500k for evaluation, anticipating that most will be between £200k and £400k.', 'https://www.nuffieldfoundation.org/funding-for-research/essential-employment-skills-fund'), who_can_apply: c('we anticipate that applications will come from collaborations between an evaluator and a delivery organisation.', 'https://www.nuffieldfoundation.org/funding-for-research/essential-employment-skills-fund') }, _walk_note: 'Large evaluation grant; the delivery charity is a partner rather than the lead. Paul to judge fit.' }) },
  { title: 'Talbot Village Trust Small Grants Programme', funder: 'Talbot Village Trust', funding_type: 'grant', apply_url: 'https://talbotvillagetrust.org/grants/small-grants-application-form/', location_tag: 'South East Dorset', is_local: true, amount_min: null, amount_max: 5000, deadline: null, is_rolling: true, eligible_structures: ORGS, impact_sectors: ['community', 'environment'], target_beneficiaries: ['general_public'],
    description: 'Grants of up to £5,000 from the Talbot Village Trust for local charities, schools and community groups in South East Dorset with an annual income under £250,000. Rolling, with decisions within five weeks, for core running costs, project expenses or small capital items. First-time applicants and environmental work particularly welcome.',
    funder_brief: b('https://talbotvillagetrust.org/grants/small-grants-application-form/', { who_can_apply: 'Charities, schools and community groups in South East Dorset with income under £250,000.', what_they_fund: 'Core costs, project costs and small capital items.', typical_award: 'Up to £5,000.', decision_timeline: 'Rolling; no deadlines; decisions within about five weeks.', how_to_apply: 'Online application form.', _citations: { decision_timeline: c('As a result, there are no application deadlines, and submissions are welcome at any time.', 'https://talbotvillagetrust.org/news/small-grants-programme-now-open-for-south-east-dorset-charities/'), open_status: c('We are delighted to announce that the Talbot Village Trust Small Grants Programme is now open and accepting applications.', 'https://talbotvillagetrust.org/news/small-grants-programme-now-open-for-south-east-dorset-charities/') } }) },
  { title: 'Drax Community Fund', funder: 'Drax', funder_type: 'corporate', funding_type: 'grant', apply_url: 'https://www.drax.com/sustainability/community-fund/', location_tag: 'Near Drax sites, UK', is_local: true, amount_min: null, amount_max: 2000, deadline: null, is_rolling: true, eligible_structures: ORGS, impact_sectors: ['community', 'education', 'environment'], target_beneficiaries: ['general_public'],
    description: 'Grants from the Drax Community Fund for local charities, schools and community groups near Drax sites in the UK, for project, core and capital costs across education, healthy living, community services, nature spaces and green energy upgrades. The page currently states UK applicants can apply for up to £2,000; the funding digest quoted £500 to £10,000. Rolling.',
    funder_brief: b('https://www.drax.com/sustainability/community-fund/', { who_can_apply: 'Charities, schools and community groups operating near Drax sites.', what_they_fund: 'Education, healthy living, community services, nature spaces and green energy upgrades.', typical_award: 'Up to £2,000 for UK applicants at present.', decision_timeline: 'Rolling.', how_to_apply: 'Eligibility checker and application on the Drax site.', _citations: { typical_award: c('Applicants in the UK can currently apply for up to £2,000.', 'https://www.drax.com/sustainability/community-fund/') }, _walk_note: 'Digest said £500 to £10,000; page says up to £2,000. Page wins.' }) },
  { title: 'Wembley Stadium Foundation Communities Fund (Liverpool City Region)', funder: 'Wembley Stadium Foundation', funding_type: 'grant', apply_url: 'https://www.wembleystadiumfoundation.org/introducing-wembley-stadium-foundation-communities-fund/', location_tag: 'Liverpool City Region', is_local: true, amount_min: null, amount_max: 5000, deadline: '2026-10-02', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['sport', 'young_people', 'creative'], target_beneficiaries: ['young_people', 'disabled', 'disadvantaged'],
    description: 'Grants of up to £5,000 from the Wembley Stadium Foundation, delivered with Everton in the Community, for local charities, community groups and sports clubs across the Liverpool City Region. Supports projects that help children and young people, particularly girls, children with disabilities and those from disadvantaged backgrounds, take part in sport, physical activity and the performing arts, building a legacy ahead of UEFA EURO 2028. Part of a £1 million, two-year programme. Closes 2 October 2026 per the funding digest.',
    funder_brief: b('https://www.wembleystadiumfoundation.org/introducing-wembley-stadium-foundation-communities-fund/', { who_can_apply: 'Charities, community groups and sports clubs in the Liverpool City Region.', what_they_fund: 'Youth sport, movement and performing arts projects reducing barriers to participation.', typical_award: 'Up to £5,000 (digest).', decision_timeline: 'Closes 2 October 2026 (digest; not read on the page).', how_to_apply: 'Through Everton in the Community, per the digest; the foundation page announces the fund.', _citations: { what_they_fund: c('We\'re proud to be investing £1 million over the next two years to support more than 100 grassroots projects and help thousands of young people get active', 'https://www.wembleystadiumfoundation.org/introducing-wembley-stadium-foundation-communities-fund/') }, _walk_note: 'Amount, deadline and application route are from the digest; the foundation page is an announcement. Find the Everton in the Community application page before publishing.' }) },
  { title: 'Reach for the Sky Challenge Fund', funder: 'Department for Transport and Civil Aviation Authority', funding_type: 'grant', apply_url: 'https://stem.caa.co.uk/reach-for-the-sky-challenge-fund', location_tag: 'England', is_local: true, amount_min: null, amount_max: null, deadline: '2026-09-18', is_rolling: false, eligible_structures: ORGS, impact_sectors: ['young_people', 'employment', 'education'], target_beneficiaries: ['young_people'],
    description: 'Grants from a £750,000 pool, run by the Department for Transport and the Civil Aviation Authority, for organisations in England running projects that support young people into aviation and aerospace careers, with a focus on breaking down barriers for underrepresented groups. Registered charities and community groups can apply for projects lasting up to one year with clear, measurable employment outcomes. Now in its fourth round. The page says the deadline has been extended; the digest gives 18 September 2026.',
    funder_brief: b('https://stem.caa.co.uk/reach-for-the-sky-challenge-fund', { who_can_apply: 'A range of eligible organisations including specialist STEM engagement providers, registered charities and community groups, in England.', what_they_fund: 'Projects supporting young people aged 16 and over into aviation and aerospace careers: outreach, careers masterclasses, mentoring, interview preparation and application support.', typical_award: 'From a £750,000 pool; individual amounts not stated on the page read.', decision_timeline: 'Deadline extended per the page; digest gives 18 September 2026.', how_to_apply: 'Through the CAA STEM site.', _citations: { open_status: c('We have extended the deadline for applications.', 'https://stem.caa.co.uk/reach-for-the-sky-challenge-fund'), what_they_fund: c('Entry-level and support roles are eligible where the project helps young people aged 16+ access and progress into the sector.', 'https://stem.caa.co.uk/reach-for-the-sky-challenge-fund') }, _walk_note: 'Exact extended deadline not captured; confirm before publishing. Closes within days.' }) },
  { title: 'BBC Radio 4 and BBC One Appeals', funder: 'BBC', funder_type: 'other', funding_type: 'in_kind', apply_url: 'https://www.bbc.co.uk/charityappeals/apply/', location_tag: 'UK', is_local: false, amount_min: null, amount_max: null, deadline: '2026-12-07', is_rolling: false, eligible_structures: ['registered_charity', 'cio'], impact_sectors: ['community'], target_beneficiaries: ['general_public'],
    description: 'Free national airtime and professional production support for a UK charity to broadcast a fundraising appeal on BBC Radio 4 or BBC One. No cash grant; featured charities raise an average of around £38,000 in public donations. Charities with income under £100,000 in their last financial year, and Disasters Emergency Committee members, are not eligible. Expressions of interest close 7 December 2026 per the funding digest.',
    funder_brief: b('https://www.bbc.co.uk/charityappeals/apply/', { who_can_apply: 'UK registered charities meeting the BBC appeal criteria; not charities with income under £100,000 or DEC members.', what_they_fund: 'Airtime and production for a fundraising appeal.', typical_award: 'No cash; average public donations of about £38,000 per appeal (digest).', decision_timeline: 'Expression of interest by 7 December 2026 (digest); decision about three months after the application deadline.', how_to_apply: 'Application via the BBC Charity Appeals site.', _citations: { exclusions: c('cannot support: Charities that are members of the Disasters Emergency Committee Charities with an income of less than £100k in their last financial year.', 'https://www.bbc.co.uk/charityappeals/apply/'), decision_timeline: c('You should be informed of the decision approximately 3 months after the application deadline.', 'https://www.bbc.co.uk/charityappeals/apply/') } }) },
]
async function main() {
  const db = getAdminDb(); console.log(APPLY ? 'APPLY' : 'DRY RUN')
  type Held = { id: string; title: string; funder: string | null; funder_type: string | null; pipeline_state: string; apply_url: string | null }
  const all: Held[] = []
  for (let from = 0; ; from += 1000) { const { data, error } = await db.from('scraped_grants').select('id,title,funder,funder_type,pipeline_state,apply_url').range(from, from + 999); if (error) throw error; all.push(...(data as Held[])); if (!data || data.length < 1000) break }
  const { count } = await db.from('scraped_grants').select('id', { count: 'exact', head: true }); if (all.length !== count) throw new Error('partial read')
  const norm = (u: string) => { const x = new URL(u); return x.hostname.replace(/^www\./, '') + x.pathname.replace(/\/$/, '') }
  let staged = 0
  for (const row of NEW) {
    if (row.deadline && (row.deadline as string) <= TODAY) throw new Error(`${row.title}: deadline not in the future`)
    const dupe = all.filter(d => { try { return d.apply_url && norm(d.apply_url) === norm(row.apply_url) } catch { return false } })
    const tdupe = all.filter(d => d.title.toLowerCase().replace(/[^a-z0-9]/g, '') === row.title.toLowerCase().replace(/[^a-z0-9]/g, '') && d.pipeline_state !== 'rejected')
    if (dupe.length || tdupe.length) { console.log(`  already_held: ${row.title} -> ${[...dupe, ...tdupe].map(d => `${d.id.slice(0, 8)} [${d.pipeline_state}]`).join('; ')}`); continue }
    const sib = all.find(d => d.funder === row.funder && d.funder_type); const funder_type = (row.funder_type as string | undefined) ?? sib?.funder_type ?? (/Government|Ministry|Department/.test(row.funder) ? 'government' : /Community Foundation/.test(row.funder) ? 'community_foundation' : 'trust_foundation')
    console.log(`  stage ${row.title} (${funder_type}) ${row.amount_min ?? '?'}-${row.amount_max ?? '?'} ${row.deadline ?? 'rolling'} ${row.location_tag}`)
    if (!APPLY) continue
    const stamped = { ...stampNewGrant({ ...row, funder_type, source: SRC, is_active: false, url_status: 'unchecked' }, SRC), pipeline_state: 'tagged_awaiting_review' as const }
    const { data, error } = await db.from('scraped_grants').insert(stamped).select('id').single(); if (error) throw error; staged++
  }
  console.log(`${APPLY ? 'staged' : 'would stage'} ${APPLY ? staged : NEW.length} of ${NEW.length}`)
}
main().catch(e => { console.error(e); process.exit(1) })
