// Accuracy pass over the 15 digest rows staged today, from full page reads.
import { getAdminDb } from '../src/lib/admin/admin-db'
import { mergeGrantUpdate, stampNewGrant } from '../src/lib/grant-merge'
const db = getAdminDb(); const S = 'user_verified:digest-review-2026-09-11' as never
const NCF_SMALL = 'Your group must be a small, locally managed, voluntary, community or self-help group with a written constitution containing a dissolution clause, and volunteers who are not on the management committee. Social enterprises with a person with significant control are not funded.'
const FIX: Record<string, { fields?: Record<string, unknown>; brief: Record<string, unknown> }> = {
  'Margaret Giffen Community Fund': { brief: { who_can_apply: NCF_SMALL + ' Based in North Northamptonshire, including Corby and Kettering.', exclusions: 'Projects with a total budget over £20,000; social enterprises with a person with significant control.', funder_tips: 'Show how the project meets at least one priority from the foundation\'s Hidden Needs report.' } },
  'The Compton Fund': { brief: { who_can_apply: NCF_SMALL + ' The group and the activity must be based and take place exclusively within Northamptonshire.', exclusions: 'Groups or activities outside Northamptonshire; social enterprises with a person with significant control.' } },
  'Northamptonshire Queen\'s Institute Relief Fund': { brief: { who_can_apply: NCF_SMALL + ' Based in Northamptonshire; the fund is now open county-wide.', exclusions: 'Renovation or building work; profit-making organisations or businesses; activities of a political nature; activities which exclusively support or promote religion; social enterprises with a person with significant control.' } },
  'The Alastair James Memorial Trust': { brief: { who_can_apply: 'Registered charities and community or voluntary groups in Northamptonshire, the East Midlands and East Anglia with an annual income of £1.5 million or less, with a written constitution containing a dissolution clause and an equalities policy. Individuals with an unfulfilled need may apply at the trustees\' discretion.', exclusions: 'Groups with income over £1.5 million; groups without an equalities policy.' } },
  'Amplius Community Fund': { brief: { who_can_apply: 'Local community organisations and social enterprises based in Northamptonshire with an annual turnover of £1 million or less, a written constitution with a dissolution clause, and work aligned to Amplius\' Purposeful Impact priorities.', exclusions: 'Turnover over £1 million; social enterprises with a single person with significant control.', typical_award: 'Up to £5,000 per the funding digest; the page states no maximum in the text read. Can be used towards capital items.' } },
  'Cecil Pettit Legacy Fund': { brief: { who_can_apply: 'Local community organisations and social enterprises based in Northamptonshire, with a written constitution containing a dissolution clause, working with people with disabilities.', exclusions: 'Social enterprises with a single person with significant control.' } },
  'African & Caribbean Elders Service Legacy Fund': { brief: { who_can_apply: 'Charities, constituted community groups, CICs or companies limited by guarantee with charitable aims, based in Northamptonshire, where 50% or more of senior management and the board represent Black and Global Majority communities, with an equality or equity and diversity policy, supporting older people from those communities.', exclusions: 'Organisations whose leadership is less than half Black and Global Majority; social enterprises with a person with significant control.', funder_tips: 'Awards must be spent within 12 months.' } },
  'Luton Innovation & Collaboration Fund': { brief: { how_to_apply: 'Book a short meeting with the BLCF team to talk through the idea and confirm eligibility before completing the application form. Full applications close Monday 5 October 2026 at midday.', funder_tips: 'This round is focused on work and skills with a £110,000 pot; collaborative ten-month projects are prioritised.' } },
  'Common Ground Award 2026 to 2027': { brief: { how_to_apply: 'A link to the application form is published on GOV.UK on 14 September 2026. Read the prospectus first; one application per organisation, individually or as a consortium.', exclusions: 'Organisations with turnover or income of £5 million or more; organisations without a UK bank account or the ability to hold property and contract; a second application from an organisation already in a consortium bid.', funder_tips: 'Grant must be spent by 31 March 2027 with a credible delivery plan; applications scoring zero on any of the five criteria are ineligible.', decision_timeline: 'Form available 14 September 2026; closing date not stated on the prospectus page, 12 October 2026 per the funding digest. Awards made as soon as possible after the window.' } },
  'Essential Employment Skills Fund': { brief: { exclusions: 'Proposals without a robust impact evaluation tracking change in the target skills and progress towards employment.', funder_tips: 'Be explicit about which essential employment skills the programme addresses; most awards will be £200,000 to £400,000.' } },
  'Talbot Village Trust Small Grants Programme': { brief: { funder_tips: 'The project must begin after the trustees\' decision; check the meeting dates on the website. A separate capital programme for awards of £10,000 or more closes 29 November 2026.', exclusions: 'Organisations with annual income over £250,000; projects starting before the trustees\' decision.' } },
  'Drax Community Fund': { brief: { how_to_apply: 'Online form on the Drax site; the eligibility checker states the amount available for your location.' } },
  'BBC Radio 4 and BBC One Appeals': { brief: { who_can_apply: 'Charities registered with the Charity Commission, OSCR or the Charity Commission for Northern Ireland whose UK work benefits more than one of England, Scotland, Wales and Northern Ireland, or whose international work has national impact in one or more low or middle-income countries.', exclusions: 'Charities with income under £100,000 in their last financial year; Disasters Emergency Committee members; charities whose work benefits only one UK nation.' } },
  'Wembley Stadium Foundation Communities Fund (Liverpool City Region)': { brief: { how_to_apply: 'Application route not yet found on the foundation site or the Everton in the Community site; hold until located.' } },
  'Reach for the Sky Challenge Fund': { brief: { how_to_apply: 'Apply through the CAA STEM site; joint applications must name a lead organisation.', decision_timeline: 'The page says the deadline has been extended but states no date in the text read; the funding digest gives 18 September 2026.' } },
}
const CAPITAL = { title: 'Talbot Village Trust Capital Programme', funder: 'Talbot Village Trust', funder_type: 'trust_foundation', funding_type: 'grant', apply_url: 'https://talbotvillagetrust.org/grants/', url_status: 'unchecked', location_tag: 'South East Dorset', is_local: true, amount_min: 10000, amount_max: null, deadline: '2026-11-29', is_rolling: false, eligible_structures: ['registered_charity', 'cio', 'cic_guarantee', 'cic_shares', 'ltd_guarantee', 'unincorporated', 'cooperative'], impact_sectors: ['community'], target_beneficiaries: ['general_public'],
  description: 'Capital grants of £10,000 or more from the Talbot Village Trust for charities and community organisations in South East Dorset. Awards in 2025 averaged £12,500; applicants requesting over £50,000 are asked to contact the trust first. Organisations must show they have, or can raise, at least 25% match funding. Closes 29 November 2026 at 11:59pm, decision mid May 2027.',
  funder_brief: { source: 'live_fetch', last_enriched: '2026-09-11', open_status: 'open', who_can_apply: 'Charities and community organisations in South East Dorset with at least 25% match funding in place or raisable.', what_they_fund: 'Capital projects.', typical_award: '£10,000 or more; 2025 awards averaged £12,500.', exclusions: 'Requests without 25% match funding.', decision_timeline: 'Closes Sunday 29 November 2026 at 11:59pm; decision mid May 2027.', how_to_apply: 'Online application via the grants page; contact the trust before applying for over £50,000.', _citations: { typical_award: { snippet: 'Capital Programme: We accept requests for grant awards of £10,000 or more.', confidence: 'high', source_url: 'https://talbotvillagetrust.org/grants/' }, exclusions: { snippet: 'your organisation will need to prove that it has - or can raise at least 25% match funding.', confidence: 'high', source_url: 'https://talbotvillagetrust.org/grants/' } }, _source_url: 'https://talbotvillagetrust.org/grants/' } }
;(async () => {
  const { data: rows } = await db.from('scraped_grants').select('id,title,funder_brief').eq('source', 'system:digest-2026-09-11')
  if (rows!.length !== 15) throw new Error('expected 15 staged rows, found ' + rows!.length)
  let n = 0
  for (const r of rows!) { const f = FIX[r.title]; if (!f) { console.log('no fix for', r.title); continue }
    const brief = { ...(r.funder_brief as Record<string, unknown>), ...f.brief }
    const res = await mergeGrantUpdate({ id: r.id, source: S, db, fields: { ...(f.fields ?? {}), funder_brief: brief } })
    const bad = res.rejected.filter(x => x.reason !== 'idempotent'); console.log(`fixed ${r.title}${bad.length ? ' BLOCKED ' + JSON.stringify(bad) : ''}`); n++ }
  const { data: d } = await db.from('scraped_grants').select('id').ilike('title', '%Talbot Village Trust Capital%')
  if (d!.length) console.log('capital already held'); else { const stamped = { ...stampNewGrant({ ...CAPITAL, source: 'system:digest-2026-09-11', is_active: false }, 'system:digest-2026-09-11'), pipeline_state: 'tagged_awaiting_review' as const }; const { error } = await db.from('scraped_grants').insert(stamped); console.log(error ? 'capital insert FAILED ' + error.message : 'staged Talbot capital programme') }
  console.log(`fixed ${n} of 15`)
})()
