// Paul's funding list, 22 Sept 2026: 45 funds; 12 already held, 2 out of
// scope (Curiosity Grant is schools only; Commonwealth Foundation funds civil
// society outside the UK), Parc Gwyn crematorium has no application route
// yet (Cabinet approved the approach, nothing to apply to). 27 staged here.
// Read by fetch and search, no model call. Where a funder's page could not be
// read (bot wall, broken cert, 404) the brief source is 'digest' and the row
// carries Paul's summary; the engine reads the page on its next pass.
//
//   npx tsx --env-file=.env.local scripts/funding-list-2026-09-22.ts [--apply]
import { getAdminDb } from '../src/lib/admin/admin-db'
import { stampNewGrant } from '../src/lib/grant-merge'
const APPLY = process.argv.includes('--apply')
const SRC = 'system:funding-list-2026-09-22'
const T = '2026-09-22'
const ALL = ['unincorporated', 'ltd_guarantee', 'cic_guarantee', 'cic_shares', 'cooperative', 'registered_charity', 'cio']
const CHAR = ['registered_charity', 'cio', 'scio']
type Row = Record<string, unknown> & { title: string; funder: string; apply_url: string }
const B = (o: Record<string, unknown>) => ({ source: 'live_fetch', last_enriched: T, open_status: 'open', ...o })
const D = (o: Record<string, unknown>) => ({ source: 'digest', last_enriched: T, open_status: 'open', ...o })
const c = (snippet: string, source_url: string, confidence = 'high') => ({ snippet, confidence, source_url })

const NEW: Row[] = [
  // ── closing this week ──
  { title: 'Rowlands Trust Grants (final round)', funder: 'The Rowlands Trust', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['capital'],
    apply_url: 'https://therowlandstrust.org.uk/', url_status: 'unchecked', location_tag: 'West Midlands and South Midlands', is_local: true,
    amount_min: 500, amount_max: 5000, deadline: '2026-09-23', is_rolling: false, eligible_structures: CHAR,
    impact_sectors: ['community', 'heritage', 'health', 'education', 'creative', 'environment'], target_beneficiaries: ['general_public', 'older_people', 'young_people'],
    description: 'Capital grants, typically £500 to £5,000, from the Rowlands Trust for registered charities and churches in Birmingham, Gloucestershire, Herefordshire, Shropshire, Warwickshire and Worcestershire: research, education and training, medical and scientific research, the armed services, people disadvantaged by education, health, finance or disability, older and young people, music and the arts, the environment, and church restoration that increases community use. The September 2026 round is the trust\'s final round of funding. Application form on request from the trust.',
    funder_brief: D({ is_local: true, location_tag: 'West Midlands and South Midlands',
      who_can_apply: 'Registered charities and churches active in Birmingham, Gloucestershire, Herefordshire, Shropshire, Warwickshire and Worcestershire.',
      typical_award: 'Typically £500 to £5,000.', decision_timeline: 'The September 2026 round is the last. Deadline 23 September 2026.',
      how_to_apply: 'Contact the trust for its application form (louise.ruane@therowlandstrust.org.uk).',
      _citations: { how_to_apply: c('Applicants must contact the Trust directly to obtain an application form', 'https://www.nationalchurchestrust.org/get-support/support-organisations/rowlands-trust', 'med') } }) },
  { title: 'United Way UK Give Local Grants 2026/27', funder: 'United Way UK', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://docs.google.com/forms/d/e/1FAIpQLSenbSbisPEDmkHTmSnjpX7QBvjPX6NyBBFScZ8GN6O2MbCy_g/viewform', url_status: 'unchecked', location_tag: 'UK (30 named towns and cities)', is_local: true,
    amount_min: 1500, amount_max: 1500, deadline: '2026-09-24', is_rolling: false, eligible_structures: ALL, max_org_income: 300000,
    impact_sectors: ['education', 'employment', 'health', 'community'], target_beneficiaries: ['people_in_poverty', 'children', 'general_public'],
    description: 'Thirty grants of £1,500, funded by Costco through United Way UK, for small organisations with an average annual income of £300,000 or less working in one of 30 named locations: 26 in England including Birmingham, Bristol, Leeds, Liverpool, Manchester and Sheffield, plus Aberdeen, Glasgow, Edinburgh and Cardiff. Priorities are long-term solutions in education, income stability and health. One grant per location. United Way is looking for organisations that could become long-term partners. Closes 24 September 2026.',
    funder_brief: B({ is_local: true, location_tag: 'UK (30 named towns and cities)',
      who_can_apply: 'Organisations with a charitable purpose and an average annual income of £300,000 or less, based in one of the 30 listed locations. Not individuals.',
      typical_award: '£1,500, thirty grants in total, one per location.', decision_timeline: 'Deadline 24 September 2026. Funds paid in the autumn.',
      how_to_apply: 'Online form linked from the Give Local page.',
      _citations: { who_can_apply: c('Organisations with an average annual income of £300,000 or less are eligible', 'https://voscur.org/give-local-2026-2027/'), decision_timeline: c('Deadline: 24th September 2026', 'https://voscur.org/give-local-2026-2027/') } }) },
  { title: 'West Suffolk Council Thriving Communities Fund 2027/28', funder: 'West Suffolk Council', funder_type: 'local_authority', funding_type: 'grant', funding_subtypes: ['project', 'core'],
    apply_url: 'https://www.westsuffolk.gov.uk/community/community-grants.cfm', url_status: 'unchecked', location_tag: 'West Suffolk', is_local: true,
    amount_min: 2000, amount_max: 20000, deadline: '2026-09-25', is_rolling: false, deadline_cycle: [{ day: 25, month: 9, label: 'Annual round closes' }], eligible_structures: ALL,
    impact_sectors: ['community', 'health', 'young_people'], target_beneficiaries: ['general_public', 'families', 'young_people'],
    description: 'Grants of £2,000 to £20,000 from West Suffolk Council for charities, community groups and voluntary organisations helping residents reach services, support and activities that improve health and wellbeing. Community grants of £2,000 to £8,000 fund one-off projects in a village or estate; larger grants of £8,001 to £20,000 fund work across the district or a whole town. Over £265,000 available for 2027/28. Focus areas include cost of living, domestic abuse trauma, loneliness, youth activities, vulnerable people and bereavement. Applications under £2,000 go to councillor locality budgets. Closes 12 noon on 25 September 2026; an annual round.',
    funder_brief: B({ is_local: true, location_tag: 'West Suffolk',
      who_can_apply: 'Community groups, charities and voluntary organisations based in or operating within West Suffolk.',
      typical_award: '£2,000 to £8,000 for local one-off projects; £8,001 to £20,000 for district-wide or town-wide work.',
      decision_timeline: 'Closes 12pm Friday 25 September 2026. Annual round, now in its third year.',
      how_to_apply: 'Editable PDF form emailed to thrivingcommunitiesfund@westsuffolk.gov.uk with supporting documents.',
      _citations: { decision_timeline: c('Deadline: 12pm Friday, 25 September 2026', 'https://www.westsuffolk.gov.uk/community/community-grants.cfm'), typical_award: c('Community grants of between £2,000 and £8,000 ... larger grants of between £8,001 and £20,000', 'https://www.westsuffolk.gov.uk/community/community-grants.cfm') } }) },
  { title: 'Thriplow Charitable Trust Grants', funder: 'Thriplow Charitable Trust', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.thriplowcharitabletrust.org/', url_status: 'unchecked', location_tag: 'UK', is_local: false,
    amount_min: 1000, amount_max: 7500, deadline: '2026-09-25', is_rolling: false, deadline_cycle: [{ day: 25, month: 9, label: 'For the October meeting' }, { day: 25, month: 3, label: 'For the spring meeting' }], eligible_structures: CHAR,
    impact_sectors: ['education', 'environment', 'heritage', 'creative'], target_beneficiaries: ['general_public'],
    description: 'Grants of £1,000 to £7,500 from the Thriplow Charitable Trust to UK registered charities for discrete projects advancing higher and further education and research: academic research, undergraduate and graduate bursaries, exhibitions, conservation and environmental research, museum and library collections, teacher training and resources in the developing world, and early-career development in the performing arts. Not for individuals, primary or secondary education, major capital projects, clinical trials, performing arts companies or consecutive-year applications. Trustees meet twice a year; the next deadline is 25 September 2026 for the meeting on 30 October 2026.',
    funder_brief: B({ is_local: false, location_tag: 'UK',
      who_can_apply: 'Charitable bodies only, with a preference for British institutions in higher education and research. No grants to individuals.',
      typical_award: 'Usually £1,000 to £7,500.', exclusions: 'Primary, secondary and early years education; major capital projects; performing arts companies; clinical trials; organisations funded in consecutive years; individuals.',
      decision_timeline: 'Applications by 25 September 2026 for the trustees\' meeting on 30 October 2026. Trustees meet twice a year.',
      how_to_apply: 'Online form on the trust\'s website, with the annual report attached; post or email also accepted.',
      _citations: { typical_award: c('Grants are usually made of amounts between £1,000-£7,500.', 'https://www.thriplowcharitabletrust.org/'), decision_timeline: c('Applications are due by September 25, 2026, with the next trustee meeting scheduled for October 30, 2026.', 'https://www.thriplowcharitabletrust.org/') } }) },
  { title: 'Peak District National Park Foundation Community Nature Fund', funder: 'Peak District National Park Foundation', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['capital'],
    apply_url: 'https://www.peakdistrictfoundation.org.uk/community-nature-fund/', url_status: 'unchecked', location_tag: 'Peak District National Park', is_local: true,
    amount_min: 500, amount_max: 5000, deadline: '2026-09-25', is_rolling: false, deadline_cycle: [{ day: 25, month: 9, label: 'Round closes' }, { day: 29, month: 1, label: 'Round closes' }, { day: 5, month: 6, label: 'Round closes' }], eligible_structures: ALL,
    impact_sectors: ['environment'], target_beneficiaries: ['general_public'],
    description: 'Grants of £500 to £5,000 from the Peak District National Park Foundation towards the capital costs of creating, improving or expanding spaces for nature inside the National Park boundary: wildflower meadows, hedgerows and trees, ponds, bird and bat boxes, and the tools, materials and contractors to deliver them. Open to parish councils, schools, charities, CIOs, CICs, community groups, societies and smallholders running not-for-profit projects. Not for running costs, overheads, core salaries, work already done, or sites already managed for nature such as SSSIs. Three rounds a year: 25 September 2026, 29 January 2027 and 5 June.',
    funder_brief: B({ is_local: true, location_tag: 'Peak District National Park',
      who_can_apply: 'Any organisation, including parish councils, schools, charities, CIOs, CICs, community groups and smallholders, for a not-for-profit project within the Peak District National Park.',
      typical_award: '£500 to £5,000 towards specific project costs.', exclusions: 'General running costs, overheads and core salaries; work already undertaken; recoverable VAT; statutory obligations; sites already managed for nature.',
      decision_timeline: 'Rounds close 25 September 2026 (results by 23 October), 29 January 2027 (results by 26 February) and 5 June (results by 3 July).',
      how_to_apply: 'Download the guidance and form, get quotes for capital costs, and email to hello@peakdistrictfoundation.org.uk.',
      _citations: { typical_award: c('Grants of between £500 and £5,000 are available towards the specific costs of delivering your project', 'https://www.peakdistrictfoundation.org.uk/community-nature-fund/'), decision_timeline: c('25th September 2026 (results by 23rd October); 29th January 2027 (results by 26th February)', 'https://www.peakdistrictfoundation.org.uk/community-nature-fund/') } }) },
  { title: 'Antrim and Newtownabbey LEP Technical Assistance Programme', funder: 'Antrim and Newtownabbey Borough Council', funder_type: 'local_authority', funding_type: 'grant', funding_subtypes: ['capacity'],
    apply_url: 'https://antrimandnewtownabbey.gov.uk/business/support-for-businesses/technical-assistance/', url_status: 'unchecked', location_tag: 'Antrim and Newtownabbey', is_local: true,
    amount_min: null, amount_max: 10000, deadline: '2026-09-25', is_rolling: false, eligible_structures: ['cic_guarantee', 'cic_shares', 'ltd_guarantee', 'cooperative', 'registered_charity', 'cio'],
    impact_sectors: ['social_economy', 'community'], target_beneficiaries: ['social_impact_orgs'],
    description: 'Grants of up to £10,000 from Antrim and Newtownabbey Borough Council\'s Local Economic Partnership for social enterprises in the borough that have operated for at least six months and want specialist technical expertise to develop or explore a workspace project: consultancy and professional support the organisation cannot provide in-house. Applicants must show match funding through bank statements and submit quotations with a full application. Previous recipients may reapply. Email applications to the council by 5pm on 25 September 2026; late or incomplete submissions are not assessed.',
    funder_brief: B({ is_local: true, location_tag: 'Antrim and Newtownabbey',
      who_can_apply: 'Social enterprises in the Antrim and Newtownabbey Borough Council area operating for at least six months, pursuing a local workspace project.',
      typical_award: 'Up to £10,000 per organisation, with match funding evidenced by bank statements.',
      decision_timeline: 'Deadline 5pm Friday 25 September 2026.', how_to_apply: 'Complete the form, attach quotations and bank statements, and email LEP@antrimandnewtownabbey.gov.uk.',
      _citations: { who_can_apply: c('been operating for a minimum of six months', 'https://antrimandnewtownabbey.gov.uk/business/support-for-businesses/technical-assistance/'), decision_timeline: c('5pm Friday, September 25', 'https://antrimandnewtownabbey.gov.uk/business/support-for-businesses/technical-assistance/') } }) },
  { title: 'Dr Guthrie\'s Association Grants', funder: 'Dr Guthrie\'s Association', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://discover.azets.co.uk/application-download-dr-guthries-association-scio', url_status: 'unchecked', location_tag: 'Scotland, preference for Edinburgh', is_local: true,
    amount_min: 250, amount_max: 2000, deadline: '2026-09-25', is_rolling: false, deadline_cycle: [{ day: 25, month: 1 }, { day: 25, month: 5 }, { day: 25, month: 9 }], eligible_structures: ALL,
    impact_sectors: ['young_people', 'children', 'employment', 'creative'], target_beneficiaries: ['children', 'young_people', 'people_in_poverty'],
    description: 'Grants, usually £2,000 or less, from Dr Guthrie\'s Association for not-for-profit organisations caring for economically and socially disadvantaged children and young people in Scotland, with preference for the Edinburgh area. Priority to small local organisations providing creative and outdoor pursuits for disadvantaged children and young people, or supporting young unemployed people, where a small grant makes a difference and other funding is hard to find. About £90,000 a year. Deadlines 25 January, 25 May and 25 September.',
    funder_brief: B({ is_local: true, location_tag: 'Scotland, preference for Edinburgh',
      who_can_apply: 'Not-for-profit organisations supporting economically and socially disadvantaged children and young people in Scotland, with preference for the Edinburgh area and for smaller charities.',
      typical_award: '£250 to £2,000; about £90,000 distributed a year.', decision_timeline: 'Deadlines 25 January, 25 May and 25 September each year.',
      how_to_apply: 'Download the form from the Azets page and send it to the grant administrator, PO Box 28838, Edinburgh EH15 2XZ, or drguthrie16@gmail.com.',
      _citations: { typical_award: c('about £90,000 is available for distribution each year and the grants are usually limited to £2,000 or less', 'https://funding.scot/funds/a0Rb0000000Ng5kEAC/dr-guthrie-s-association', 'med'), decision_timeline: c('Deadlines for applications are 25 January, 25 May and 25 September each year', 'https://funding.scot/funds/a0Rb0000000Ng5kEAC/dr-guthrie-s-association', 'med') } }) },
  { title: 'Enhancing Pembrokeshire Grant', funder: 'Pembrokeshire County Council', funder_type: 'local_authority', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.pembrokeshire.gov.uk/enhancing-pembrokeshire-grant-funding-criteria/enhancing-pembrokeshire-grant-funding-criteria', url_status: 'unchecked', location_tag: 'Pembrokeshire', is_local: true,
    amount_min: null, amount_max: 15000, deadline: '2026-09-26', is_rolling: false, deadline_cycle: [{ day: 26, month: 9, label: 'Expressions of interest close' }], eligible_structures: ALL,
    impact_sectors: ['community', 'housing'], target_beneficiaries: ['general_public'],
    description: 'Small grants of up to £15,000 from Pembrokeshire County Council, funded by the second homes council tax premium, for new projects that address the impact of second homes and strengthen local communities. Constituted community groups, registered charities, social enterprises and town and community councils can apply. Two stages: register the project and request an expression of interest form by email, then a full application by invitation. Expressions of interest for the current round close at 11am on 26 September 2026.',
    funder_brief: D({ is_local: true, location_tag: 'Pembrokeshire',
      who_can_apply: 'Constituted community groups, registered charities, social enterprises and town and community councils in Pembrokeshire.',
      typical_award: 'Up to £15,000.', decision_timeline: 'Expressions of interest by 11am on 26 September 2026; full applications by invitation in October.',
      how_to_apply: 'Email enhancing.pembrokeshire@pembrokeshire.gov.uk to register the project and request an expression of interest form.',
      _citations: { who_can_apply: c('constituted community groups, charities, social enterprises, Town and Community Councils', 'https://newsroom.pembrokeshire.gov.uk/news/next-round-of-enhancing-pembrokeshire-funds-open-for-expressions-of-interest', 'med') } }) },
  { title: 'Electrical Safety Fund 2026', funder: 'Electrical Safety First', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.electricalsafetyfirst.org.uk/electricalsafetyfund', url_status: 'unchecked', location_tag: 'UK', is_local: false,
    amount_min: null, amount_max: 10000, deadline: '2026-09-27', is_rolling: false, deadline_cycle: [{ day: 27, month: 9, label: 'Annual round closes' }], eligible_structures: ALL,
    impact_sectors: ['community', 'housing', 'health'], target_beneficiaries: ['general_public', 'older_people'],
    description: 'Grants of up to £10,000 from Electrical Safety First, from a £1 million fund, for UK not-for-profit and public organisations, including charities, CICs, schools, housing providers, emergency services and councils, to deliver projects that reduce the risk of electrical accidents: product testing and repair events, awareness campaigns, educational workshops, community outreach and home safety visits. In its fifth year the maximum grant rose from £5,000 to £10,000. Applications 17 August to 27 September 2026 through the grants portal.',
    funder_brief: B({ is_local: false, location_tag: 'UK',
      who_can_apply: 'UK-based not-for-profit and public organisations: charities, schools, government bodies, CICs and trusts.',
      typical_award: 'Up to £10,000 from a £1 million fund.', decision_timeline: 'Open 17 August to 27 September 2026.',
      how_to_apply: 'Register and apply through grants.electricalsafetyfirst.org.uk.',
      _citations: { decision_timeline: c('Application Period: August 17 - September 27, 2026', 'https://www.electricalsafetyfirst.org.uk/electricalsafetyfund'), typical_award: c('grants of up to £10,000 available', 'https://grantfinder.co.uk/electrical-safety-fund-invites-applications-for-2026-funding-round/', 'med') } }) },
  { title: 'Active Thames Fund', funder: 'Port of London Authority', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://activethames.co.uk/', url_status: 'unchecked', location_tag: 'Greater London, Kent and Essex', is_local: true,
    amount_min: null, amount_max: null, amount_undisclosed: true, deadline: '2026-09-27', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['sport', 'health', 'environment'], target_beneficiaries: ['general_public', 'young_people', 'disabled_people'],
    description: 'Grants from the Port of London Authority\'s Active Thames partnership for formally constituted not-for-profit and statutory organisations that get more people active on and beside the tidal Thames, the Thames Path National Trail and inland waterways across Greater London, Kent and Essex. Priority to widening participation among under-represented groups, developing coaches and volunteers, and physical and mental wellbeing. No fixed maximum is published; most past grants were around £5,000, and requests above that should meet several fund objectives. Multi-year funding was introduced in 2026. Applications close 27 September 2026, with decisions in December and delivery from spring 2027.',
    funder_brief: D({ is_local: true, location_tag: 'Greater London, Kent and Essex',
      who_can_apply: 'Formally constituted not-for-profit or statutory organisations operating along waterways or blue space in Greater London, Kent or Essex. Not individuals.',
      typical_award: 'No fixed maximum; most grants around £5,000, larger requests where delivery is strong and several objectives are met.',
      decision_timeline: 'Closes 27 September 2026. Decisions in December; delivery from spring 2027.', how_to_apply: 'Apply on the Active Thames website.',
      _citations: { who_can_apply: c('Applicants must be formally constituted not-for-profit or statutory organisations operating along waterways or blue space in Greater London, Kent or Essex', 'https://pla.co.uk/Active-Thames-Fund', 'med') } }) },
  { title: 'Thames Valley PCC Community Fund', funder: 'Thames Valley Police and Crime Commissioner', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.thamesvalley-pcc.gov.uk/get-involved/community-fund', url_status: 'unchecked', location_tag: 'Berkshire, Buckinghamshire, Milton Keynes and Oxfordshire', is_local: true,
    amount_min: null, amount_max: 10000, deadline: '2026-09-28', is_rolling: false, deadline_cycle: [{ day: 28, month: 9, label: 'Autumn round closes' }, { day: 28, month: 2, label: 'Spring round closes' }], eligible_structures: ALL,
    impact_sectors: ['justice', 'community'], target_beneficiaries: ['general_public', 'young_people'],
    description: 'Grants of up to £10,000 from the Thames Valley Police and Crime Commissioner, from about £200,000 a round raised from the sale of items seized from criminals, for not-for-profit voluntary and community organisations, including town and parish councils, social enterprises and charities, across Berkshire, Buckinghamshire, Milton Keynes and Oxfordshire. Projects must support the Police and Crime Plan: protecting communities (crime prevention, road safety), protecting people (abuse, exploitation, the night-time economy) and protecting property (cybercrime, fraud, retail crime). Two rounds a year. The current round closes at 12pm on Monday 28 September 2026.',
    funder_brief: B({ is_local: true, location_tag: 'Berkshire, Buckinghamshire, Milton Keynes and Oxfordshire',
      who_can_apply: 'Not-for-profit voluntary and community sector organisations, including town and parish councils, social enterprises, companies limited by guarantee and registered charities, in the Thames Valley.',
      typical_award: 'Up to £10,000; about £200,000 per round.', decision_timeline: 'Closes 12pm Monday 28 September 2026; successful applicants attend a presentation on 26 November 2026. Two rounds a year, spring and autumn.',
      how_to_apply: 'Online application form on the Community Fund page, after reading the guidance and FAQs.',
      _citations: { decision_timeline: c('Applications are open through Monday 28 September 2026 at 12pm', 'https://www.thamesvalley-pcc.gov.uk/get-involved/community-fund'), typical_award: c('Community and voluntary organisations can apply for grants of up to £10,000', 'https://www.thamesvalley-pcc.gov.uk/news/community-groups-invited-200000-seized-from-criminals-support-policing-priorities/') } }) },
  { title: 'Blackburn with Darwen Community Fund', funder: 'Community CVS', funder_type: 'community_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.communitycvs.org.uk/resource/funding-resources/blackburn-with-darwen-community-fund/', url_status: 'unchecked', location_tag: 'Blackburn with Darwen', is_local: true,
    amount_min: null, amount_max: 1000, deadline: '2026-09-28', is_rolling: false, deadline_cycle: [{ day: 2, month: 2, label: 'Round closes' }, { day: 1, month: 5, label: 'Round closes' }, { day: 28, month: 9, label: 'Round closes' }], eligible_structures: ['unincorporated', 'registered_charity', 'cio', 'cic_guarantee', 'ltd_guarantee'],
    impact_sectors: ['community'], target_beneficiaries: ['general_public'],
    description: 'Grants of up to £1,000 per group per calendar year, run by Community CVS for Blackburn with Darwen Borough Council, the Brian Mercer Trust and the Eric Wright Charitable Trust, for volunteer-led community groups whose activities benefit Blackburn with Darwen residents. Groups need a constitution, a committee of three or more unrelated people and a bank account with two signatories, and must be run by volunteers. Revenue-focused. Three rounds a year; the next closes at 12 noon on Monday 28 September 2026, with decisions within a month.',
    funder_brief: B({ is_local: true, location_tag: 'Blackburn with Darwen',
      who_can_apply: 'Volunteer-led, constituted community groups with a committee of three or more unrelated people and their own bank account, running activities in Blackburn with Darwen. Not statutory bodies or private organisations.',
      typical_award: 'Up to £1,000 per calendar year.', decision_timeline: 'Rounds close 2 February, 1 May and 28 September 2026 at 12 noon; decisions within one month.',
      how_to_apply: 'Download the application form from the Community CVS website and submit by the deadline; cvsgrants@communitycvs.org.uk.',
      _citations: { typical_award: c('Groups may apply for up to £1000 per calendar year.', 'https://www.communitycvs.org.uk/resource/funding-resources/blackburn-with-darwen-community-fund/'), decision_timeline: c('Round 19: Monday, September 28th (12 noon)', 'https://www.communitycvs.org.uk/resource/funding-resources/blackburn-with-darwen-community-fund/') } }) },
  { title: 'PAVS Community Warm Spaces Fund (SCAF Round 10)', funder: 'Pembrokeshire Association of Voluntary Services', funder_type: 'community_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.pavs.org.uk/community-warm-spaces-fund-scaf-round-10-summer-2026-now-open/', url_status: 'unchecked', location_tag: 'Pembrokeshire', is_local: true,
    amount_min: null, amount_max: 2500, deadline: '2026-09-28', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['community', 'health', 'mental_health'], target_beneficiaries: ['older_people', 'carers', 'people_in_poverty', 'general_public'],
    description: 'Revenue grants of up to £2,500, managed by PAVS with Pembrokeshire County Council and Welsh Government, for constituted voluntary and community groups, social enterprises and town and community councils in Pembrokeshire supporting vulnerable people: addressing disadvantage, loneliness and isolation, providing warm community spaces, supporting unpaid carers, and improving mental and physical wellbeing. Up to 100 per cent of eligible revenue costs, with limited directly related equipment. One round for 2026/27, closing 12 noon on Monday 28 September 2026; all funding spent by 31 March 2027. Projects that show how they address disadvantage are prioritised.',
    funder_brief: B({ is_local: true, location_tag: 'Pembrokeshire',
      who_can_apply: 'Constituted voluntary and community groups, social enterprises and town and community councils in Pembrokeshire.',
      typical_award: 'Up to £2,500, revenue.', decision_timeline: 'Closes 12 noon Monday 28 September 2026. Spend by 31 March 2027.',
      how_to_apply: 'Application pack on the PAVS website under Apply for Funds; development@pavs.org.uk for guidance.',
      _citations: { who_can_apply: c('Constituted voluntary, community groups, social enterprises and Town and Community Councils', 'https://www.pavs.org.uk/community-warm-spaces-fund-scaf-round-10-summer-2026-now-open/'), decision_timeline: c('Application Deadline: Monday, September 28, 2026', 'https://www.pavs.org.uk/community-warm-spaces-fund-scaf-round-10-summer-2026-now-open/') } }) },
  // ── open now, closing in October and November ──
  { title: 'WMCA Circular Economy Call to Action Fund', funder: 'West Midlands Combined Authority', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.wmca.org.uk/what-we-do/environment-energy/community-environment-fund/', url_status: 'unchecked', location_tag: 'West Midlands Combined Authority area', is_local: true,
    amount_min: null, amount_max: 5000, deadline: '2026-10-04', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['environment', 'community'], target_beneficiaries: ['general_public'],
    description: 'Grants of up to £5,000 from the West Midlands Combined Authority\'s £100,000 Circular Economy Call to Action Fund for community groups, charities, CICs and social enterprises that are members of the Community Environment Network, for community-led projects that repair, reuse and reduce waste: repair cafes, swap shops, libraries of things, school workshops and awareness activities that keep resources in use, save residents money, build skills and leave a legacy. Closes 23:59 on 4 October 2026.',
    funder_brief: D({ is_local: true, location_tag: 'West Midlands Combined Authority area',
      who_can_apply: 'Community groups, charities, CICs and social enterprises in the WMCA area that are members of the Community Environment Network.',
      typical_award: 'Up to £5,000 from a £100,000 fund.', decision_timeline: 'Closes 4 October 2026 at 23:59.',
      how_to_apply: 'Through the WMCA Community Environment Fund pages; communityenvironmentfund@wmca.org.uk.',
      _citations: { typical_award: c('Groups can apply for up to £5,000 from the grant, which is being given out by the West Midlands Combined Authority (WMCA) as part of its Circular Economy Call to Action Fund', 'https://www.expressandstar.com/news/repair-clubs-and-swap-shops-among-groups-eligible-for-mayor-parkers-ps100000-grant-scheme-9046610', 'med') } }) },
  { title: 'West Lothian Communities Mental Health and Wellbeing Fund micro-grants 2026/27', funder: 'Voluntary Sector Gateway West Lothian', funder_type: 'community_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.voluntarysectorgateway.org/year-6-communities-mental-health-and-wellbeing-fund-micro-grants-coming-soon/', url_status: 'unchecked', location_tag: 'West Lothian', is_local: true,
    amount_min: 500, amount_max: 2500, deadline: '2026-10-05', is_rolling: false, eligible_structures: ALL, max_org_income: 1000000,
    impact_sectors: ['mental_health', 'community'], target_beneficiaries: ['general_public', 'people_in_poverty', 'ethnic_minorities', 'lgbtq', 'women_girls'],
    description: 'Micro-grants of £500 to £2,500 from a £26,500 pot, run by Voluntary Sector Gateway West Lothian under the Scottish Government\'s Communities Mental Health and Wellbeing Fund, for small grassroots organisations with turnover under £1 million delivering community-based mental health activity for adults in West Lothian: tackling inequality, isolation and loneliness, suicide prevention, poverty and socio-economic disadvantage, with priority groups including people bereaved, women experiencing gender-based violence, minority ethnic communities, people with neurological conditions and LGBTI people. Capital or revenue costs. Applications 7 September to 5 October 2026.',
    funder_brief: B({ is_local: true, location_tag: 'West Lothian',
      who_can_apply: 'Voluntary and third sector organisations operating in West Lothian with turnover below £1 million.',
      typical_award: '£500 to £2,500; £26,500 in total.', decision_timeline: 'Applications 7 September to 5 October 2026.',
      how_to_apply: 'Online form on the VSGWL website; vsg@vsgwl.org or 01506 650111.',
      _citations: { typical_award: c('grants of between £500 and £2,500', 'https://theedinburghreporter.co.uk/2026/09/new-mental-health-and-welfare-fund-launched-in-west-lothian/', 'med'), decision_timeline: c('from 7 September to 5 October 2026', 'https://theedinburghreporter.co.uk/2026/09/new-mental-health-and-welfare-fund-launched-in-west-lothian/', 'med') } }) },
  { title: 'Norfolk Community Foundation Resilience Through Food Fund', funder: 'Norfolk Community Foundation', funder_type: 'community_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.norfolkfoundation.com/funding-support/grants/groups/resilience-through-food-fund/', url_status: 'unchecked', location_tag: 'Norfolk', is_local: true,
    amount_min: 5000, amount_max: 30000, deadline: '2026-10-14', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['food', 'financial', 'community'], target_beneficiaries: ['people_in_poverty', 'disabled_people', 'older_people', 'carers', 'families'],
    description: 'Grants of £5,000 to £30,000 from Norfolk Community Foundation for VCSE organisations across Norfolk delivering integrated neighbourhood food projects between December 2026 and September 2027. Funded work must combine affordable food provision, financial resilience advice (budgeting, financial literacy, employment support) and community-building activity that creates informal safety nets. Priority for low-income households, disabled people, pensioners, unpaid carers, care leavers, single-parent families and people facing one-off financial shocks. Food vouchers can be up to 10 per cent of a request. Closes 12 noon on 14 October 2026; spend by 30 September 2027.',
    funder_brief: B({ is_local: true, location_tag: 'Norfolk',
      who_can_apply: 'Voluntary, community and social enterprise organisations in Breckland, Broadland, Great Yarmouth, King\'s Lynn and West Norfolk, North Norfolk, Norwich and South Norfolk.',
      typical_award: '£5,000 to £30,000.', decision_timeline: 'Closes 14 October 2026 at 12 noon. Delivery December 2026 to September 2027.',
      how_to_apply: 'Online through the Norfolk Community Foundation grants pages.',
      _citations: { typical_award: c('£5,000-£30,000', 'https://www.norfolkfoundation.com/funding-support/grants/groups/'), decision_timeline: c('Deadline: 14 October 2026', 'https://www.norfolkfoundation.com/funding-support/grants/groups/') } }) },
  { title: 'Stop Loan Sharks POCA Community Grants 2026/27', funder: 'England Illegal Money Lending Team', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.stoploansharks.co.uk/poca-funding/', url_status: 'unchecked', location_tag: 'England', is_local: false,
    amount_min: null, amount_max: 5000, deadline: '2026-10-16', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['financial', 'justice', 'community'], target_beneficiaries: ['people_in_poverty', 'general_public'],
    description: 'Grants of up to £5,000 from the England Illegal Money Lending Team, funded by money seized from convicted loan sharks under the Proceeds of Crime Act, for community projects across England that raise awareness of the dangers of illegal money lending, prevent crime and disorder, promote the Stop Loan Sharks message and the team\'s work, and encourage reporting. Open to residents, charities, community and voluntary groups, schools and statutory agencies. Priorities are innovation, community engagement, impact and legacy. Deadline 16 October 2026.',
    funder_brief: B({ is_local: false, location_tag: 'England',
      who_can_apply: 'Local residents, charities, community and voluntary groups, schools and statutory agencies in England.',
      typical_award: 'Up to £5,000.', decision_timeline: 'The 2026/27 round closes 16 October 2026.',
      how_to_apply: 'Download the 2026-27 POCA form and FAQs from the Stop Loan Sharks website.',
      _citations: { who_can_apply: c('local residents, charities, community and voluntary groups, schools and statutory agencies', 'https://www.stoploansharks.co.uk/poca-funding/'), typical_award: c('up to £5,000', 'https://www.stoploansharks.co.uk/poca-funding/') } }) },
  { title: 'East Lindsey Pride in Place Larger Grant Scheme', funder: 'East Lindsey District Council', funder_type: 'local_authority', funding_type: 'grant', funding_subtypes: ['capital', 'project'],
    apply_url: 'https://www.e-lindsey.gov.uk/LGGF', url_status: 'unchecked', location_tag: 'East Lindsey', is_local: true,
    amount_min: 35000, amount_max: null, deadline: '2026-10-23', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['community', 'heritage', 'sport'], target_beneficiaries: ['general_public'],
    description: 'Grants of over £35,000 from the East Lindsey Investment Fund\'s Pride in Place Larger Grant Scheme, backed by £500,000, for larger strategic projects in East Lindsey, Lincolnshire that benefit a significant share of residents or make a strong contribution to local growth and pride in place. Past investments include the Skegness foreshore, Woodhall Spa town centre and Bolingbroke Castle. Awards in late 2026 for delivery by February 2028. Deadline 23 October 2026.',
    funder_brief: D({ is_local: true, location_tag: 'East Lindsey',
      who_can_apply: 'Organisations delivering larger strategic community projects in East Lindsey; see the council\'s Local Growth and Grant Funding pages.',
      typical_award: 'Over £35,000, from a £500,000 pot.', decision_timeline: 'Deadline 23 October 2026; awards late 2026; delivery by February 2028.',
      how_to_apply: 'Through the council\'s Local Growth and Grant Funding pages.',
      _citations: { typical_award: c('the ELIF Pride in Place Larger Grant Scheme which offers grants of over £35,000 for larger, strategic community projects', 'https://www.e-lindsey.gov.uk/article/29079/Two-new-Pride-in-Place-grant-schemes-funded-by-the-East-Lindsey-Investment-Fund-open-for-applications', 'med') } }) },
  { title: 'Miller Homes Community Fund', funder: 'Miller Homes', funder_type: 'corporate', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.millerhomes.co.uk/corporate/community-fund', url_status: 'unchecked', location_tag: 'England and Scotland, near Miller Homes developments', is_local: true,
    amount_min: 250, amount_max: 2000, deadline: '2026-10-28', is_rolling: false, deadline_cycle: [{ day: 29, month: 4, label: 'Spring round closes' }, { day: 28, month: 10, label: 'Autumn round closes' }], eligible_structures: ALL,
    impact_sectors: ['community', 'education', 'health', 'environment', 'sport'], target_beneficiaries: ['general_public'],
    description: 'Grants of £250 to £2,000 from Miller Homes for small local initiatives that strengthen neighbourhoods near its developments in Scotland, the North West, North East, Teesside, Yorkshire, the East, South and West Midlands, the South and the South West: projects linked to education, wellbeing, environmental improvement or participation in sport. Applicants must be UK-registered organisations with a UK bank account; no individuals. Reviewed twice a year by employee Community Fund Ambassadors. The current round runs 16 September to 28 October 2026.',
    funder_brief: B({ is_local: true, location_tag: 'England and Scotland, near Miller Homes developments',
      who_can_apply: 'UK-registered organisations with a UK bank account, in an area where Miller Homes operates. Not individuals.',
      typical_award: '£250 to £2,000.', decision_timeline: 'Current round 16 September to 28 October 2026; two rounds a year.',
      how_to_apply: 'Online form during the funding window.',
      _citations: { decision_timeline: c('Wednesday 16 September until Wednesday 28 October 2026', 'https://www.millerhomes.co.uk/corporate/community-fund'), typical_award: c('minimum of £250 up to a maximum of £2,000', 'https://www.millerhomes.co.uk/corporate/community-fund') } }) },
  { title: 'UKRI Innovation in Play to Improve Child Outcomes', funder: 'UK Research and Innovation', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://apply-for-innovation-funding.service.gov.uk/competition/2573/overview/0260e1f5-c985-4858-aee3-57a9e56f19fe', url_status: 'unchecked', location_tag: 'UK', is_local: false,
    amount_min: null, amount_max: null, amount_undisclosed: true, deadline: '2026-10-28', is_rolling: false, eligible_structures: [...ALL, 'ltd_shares'],
    impact_sectors: ['children', 'education', 'social_innovation'], target_beneficiaries: ['children', 'young_people', 'families'],
    description: 'A £3 million UKRI innovation competition for organisations of any size, including businesses, charities, not-for-profits and academic bodies, to develop practical solutions that reignite the importance of play and widen access to high-quality real-world play experiences, particularly in the home learning environment, improving children\'s cognitive, social, emotional and physical development. A single legal entity applies, with subcontractors if needed. Opens 15 September and closes 28 October 2026 at 11am. Per-project amounts are not published.',
    funder_brief: B({ is_local: false, location_tag: 'UK',
      who_can_apply: 'Organisations of any size: businesses, charities, not-for-profits, academic bodies and international organisations, applying as a single legal entity.',
      typical_award: 'A share of £3 million inclusive of VAT; no per-project figure published.', decision_timeline: 'Opens 15 September 2026, closes 28 October 2026 at 11am.',
      how_to_apply: 'Through the Innovation Funding Service.',
      _citations: { decision_timeline: c('Opening Date: 15 September 2026. Closing Date: 28 October 2026', 'https://apply-for-innovation-funding.service.gov.uk/competition/2573/overview/0260e1f5-c985-4858-aee3-57a9e56f19fe'), typical_award: c('£3 million (inclusive of VAT)', 'https://apply-for-innovation-funding.service.gov.uk/competition/2573/overview/0260e1f5-c985-4858-aee3-57a9e56f19fe') } }) },
  { title: 'National Garden Scheme Community Garden Grants 2027', funder: 'National Garden Scheme', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['capital', 'project'],
    apply_url: 'https://ngs.org.uk/who-we-are/community-garden-grants/', url_status: 'unchecked', location_tag: 'England, Wales and Northern Ireland', is_local: false,
    amount_min: 1500, amount_max: 5000, deadline: '2026-10-30', is_rolling: false, next_open_date: '29 September 2026', deadline_cycle: [{ day: 30, month: 10, label: 'Annual window closes' }], eligible_structures: ALL,
    impact_sectors: ['environment', 'community', 'health'], target_beneficiaries: ['general_public'],
    description: 'Grants of £1,500 or £5,000 from the National Garden Scheme, supported by the Julia Rausing Trust, for community gardening projects in England, Wales and Northern Ireland that increase access to green space and the health benefits of gardening. Pays for plants and containers, materials for beds and hard landscaping, greenhouses, polytunnels and sheds, seating, tools and refreshments. Established community groups, registered charities and CICs apply in a two-part process; only the first 300 eligible submissions are considered. £294,241 went to 118 projects last year. Applications for 2027 open Tuesday 29 September and close Friday 30 October 2026.',
    funder_brief: B({ is_local: false, location_tag: 'England, Wales and Northern Ireland',
      who_can_apply: 'Established community groups, registered charities and CICs running community gardening projects in England, Wales or Northern Ireland.',
      typical_award: '£1,500 or £5,000. Only the first 300 eligible submissions are considered.', decision_timeline: 'Applications open 29 September and close 30 October 2026, for 2027 grants.',
      how_to_apply: 'Two-part online process from the NGS website after reading the guidelines.',
      _citations: { decision_timeline: c('Applications for 2027 Community Garden Grants will be open between Tuesday 29 September and Friday 30 October, 2026.', 'https://ngs.org.uk/who-we-are/community-garden-grants/') } }) },
  { title: 'TEEEM Foundation Community Impact Grant 2026', funder: 'TEEEM Foundation', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://www.teeem.org/foundation', url_status: 'unchecked', location_tag: 'International', is_local: false,
    amount_min: 3700, amount_max: 22000, deadline: '2026-11-01', is_rolling: false, eligible_structures: CHAR.concat(['cic_guarantee', 'ltd_guarantee']),
    impact_sectors: ['international', 'education', 'health', 'employment', 'community'], target_beneficiaries: ['people_in_poverty', 'young_people', 'general_public'],
    description: 'Grants in three tiers from the US-based TEEEM Foundation for nonprofit and charitable organisations anywhere in the world delivering sustainable, community-led solutions: Community Grants of US$5,000 to US$10,000, Growth Grants of US$10,000 to US$20,000 and Transformational Grants of US$20,000 to US$30,000 (roughly £3,700 to £22,000; the sterling figures are approximate). Focus on education and youth development, health and essential needs, equality and empowerment, entrepreneurship and economic opportunity, and community infrastructure. Applicants must show measurable impact, strong leadership and sound finances. Applications 17 August to 1 November 2026, as a single PDF by email.',
    funder_brief: B({ is_local: false, location_tag: 'International',
      who_can_apply: 'Nonprofit and charitable organisations working to improve lives and strengthen communities around the world; those working with underserved communities and young people are encouraged.',
      typical_award: 'US$5,000 to US$30,000 across three tiers. Sterling figures on the card are approximate.', decision_timeline: 'Application window 17 August to 1 November 2026.',
      how_to_apply: 'Download and complete the application, combine it with supporting documents into one PDF, and email it by 1 November 2026.',
      _citations: { typical_award: c('Community Grants: $5,000-$10,000; Growth Grants: $10,000-$20,000; Transformational Grants: $20,000-$30,000', 'https://www.teeem.org/foundation'), decision_timeline: c('Application window: August 17 - November 1, 2026', 'https://www.teeem.org/foundation') } }) },
  { title: 'Barclays Community Sport Fund: Female Coaches for Girls Grant', funder: 'Barclays', funder_type: 'corporate', funding_type: 'grant', funding_subtypes: ['capacity'],
    apply_url: 'https://sported.org.uk/barclays-female-coaches-for-girls/', url_status: 'unchecked', location_tag: 'UK', is_local: false,
    amount_min: 200, amount_max: 400, deadline: '2026-11-04', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['sport'], target_beneficiaries: ['women_girls', 'young_people'], niche_tags: ['women_in_sport'],
    description: '£200 per coach, for up to two coaches per club, from the Barclays Community Sport Fund via Sported, to pay for a Level 1 or equivalent introductory coaching qualification plus safeguarding and first aid in football, cricket or tennis. For not-for-profit clubs and groups in England, Scotland, Wales or Northern Ireland delivering women\'s or girls\' activity, applying on behalf of female coaches aged 16 or over (18 where the course requires) who are coaching or ready to start and can complete within 12 months. Open 8 July to 5pm on 4 November 2026, closing early if demand is high. Not for higher-level qualifications or futsal, Gaelic football, padel or pickleball.',
    funder_brief: B({ is_local: false, location_tag: 'UK',
      who_can_apply: 'Not-for-profit charities, community groups, youth groups and sports clubs across the UK running football, cricket or tennis activity for women or girls, applying on behalf of a named female coach.',
      typical_award: '£200 per coach, maximum two coaches per organisation.', decision_timeline: 'Open 9am 8 July 2026 to 5pm 4 November 2026, or earlier if demand is high. Decisions within four weeks.',
      how_to_apply: 'Online through Sported, with a governing document or charity or company number and a recent bank statement.',
      _citations: { typical_award: c('£200 to cover the cost of a Level 1 or equivalent introductory qualification', 'https://sported.org.uk/barclays-female-coaches-for-girls/'), decision_timeline: c('from 9am on Wednesday 8th July 2026 until 5pm on Wednesday 4th November 2026', 'https://sported.org.uk/barclays-female-coaches-for-girls/') } }) },
  { title: 'LGBT+ Fund Get Active Fund', funder: 'LGBT+ Fund (Consortium)', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['project', 'multi_year'],
    apply_url: 'https://lgbtfund.org.uk/live-funds/', url_status: 'unchecked', location_tag: 'UK', is_local: false,
    amount_min: 5000, amount_max: 50000, deadline: '2026-11-04', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['sport', 'health', 'community'], target_beneficiaries: ['lgbtq', 'disabled_people', 'older_people', 'ethnic_minorities', 'women_girls'],
    description: 'A £400,000 fund from the LGBT+ Fund, powered by Consortium with the London Marathon Foundation, for LGBT+ led non-profit organisations and grassroots groups across the UK that deliver sport or physical activity and have run for at least six months. Grants of £5,000 to £25,000 for one year or £10,000 to £50,000 over two years. Priority for groups serving LGBT+ people facing extra barriers: LGBTQIA+ women, disabled and neurodivergent people, older people, people of faith, people from the global majority, and trans, non-binary and intersex people. Any activity that gets people moving counts, from football and dance to gardening and skateboarding. Opened 9 September, closes 12 noon on 4 November 2026; decisions early February 2027.',
    funder_brief: D({ is_local: false, location_tag: 'UK',
      who_can_apply: 'UK-based LGBT+ led non-profit groups and organisations, led by and for LGBT+ people, regularly delivering sport or physical activity and running for at least six months.',
      typical_award: '£5,000 to £25,000 a year for one year, or £10,000 to £50,000 in total over two years.', decision_timeline: 'Closes 12pm on 4 November 2026. Decisions expected early February 2027.',
      how_to_apply: 'Through the LGBT+ Fund website.',
      _citations: { typical_award: c('Up to £25,000 for 1 year or £50,000 for 2 years', 'https://grantfinder.co.uk/lgbt-get-active-grants-open-for-uk-grassroots-groups/', 'med'), decision_timeline: c('The deadline is 12pm on 4th November 2026', 'https://grantfinder.co.uk/lgbt-get-active-grants-open-for-uk-grassroots-groups/', 'med') } }) },
  { title: 'Pearce Foundation Partnerships 2027', funder: 'The Pearce Foundation', funder_type: 'trust_foundation', funding_type: 'grant', funding_subtypes: ['capacity'],
    apply_url: 'https://www.pearcefoundation.org.uk/apply', url_status: 'unchecked', location_tag: 'Sussex', is_local: true,
    amount_min: null, amount_max: 2000, deadline: '2026-11-15', is_rolling: false, deadline_cycle: [{ day: 15, month: 11, label: 'Annual cohort closes' }], eligible_structures: ALL, max_org_income: 50000,
    impact_sectors: ['community', 'social_economy'], target_beneficiaries: ['social_impact_orgs'],
    description: 'A package of financial and personal support worth up to £2,000 from the Pearce Foundation for small, early-stage charities, CICs and other not-for-profit social enterprises working only in Sussex, operating for two years or less with an income under £50,000 a year. The foundation pays for agreed services, training or equipment directly rather than transferring cash, and runs a nine-month partnership from mid-February to the end of October with up to six organisations a year. Applications for the 2027 cohort are open until 5pm on 15 November 2026, with shortlisting, a meeting in January and decisions by late January.',
    funder_brief: B({ is_local: true, location_tag: 'Sussex',
      who_can_apply: 'Small fledgling charities and not-for-profit organisations working exclusively in Sussex, operating for two years or less, with an income under £50,000 a year.',
      typical_award: 'Financial and personal support worth up to £2,000, paid for directly rather than as a cash grant; up to six partners a year.',
      decision_timeline: 'Applications open until 5pm on 15 November 2026; meetings in January; decisions by late January; partnership mid-February to October 2027.',
      how_to_apply: 'Online application from the foundation\'s Apply page, after the eligibility quiz.',
      _citations: { decision_timeline: c('Applications for our 2027 cohort are now open ... 5pm on 15 November 2026', 'https://www.pearcefoundation.org.uk/apply'), who_can_apply: c('Organisations will have been operating for two years or less, with an income of less than £50,000 a year', 'https://www.pearcefoundation.org.uk/who-we-support', 'med') } }) },
  { title: 'Historic England Neighbourhood Heritage: Grants for Communities', funder: 'Historic England', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['project'],
    apply_url: 'https://historicengland.org.uk/advice/grants/', url_status: 'unchecked', location_tag: 'England', is_local: false,
    amount_min: null, amount_max: 15000, deadline: '2026-11-27', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['heritage', 'community'], target_beneficiaries: ['people_in_poverty', 'ethnic_minorities', 'disabled_people', 'lgbtq', 'general_public'],
    description: 'Around 21 grants of up to £15,000 from Historic England for community-led projects in England that use heritage to help local people understand, influence and shape the future of their neighbourhoods. Projects must be co-created with local communities, take place in an area ranked 1 to 3 on the Index of Multiple Deprivation, and work with under-represented groups including people facing socio-economic disadvantage, minority ethnic communities, disabled and neurodivergent people, LGBTQ+ communities and people facing barriers to local decision-making. Open to heritage and non-heritage organisations with strong community connections. Deadline 27 November 2026; decisions by the end of January 2027.',
    funder_brief: D({ is_local: false, location_tag: 'England',
      who_can_apply: 'Heritage and non-heritage organisations with strong community connections, for co-created projects in IMD decile 1 to 3 areas of England.',
      typical_award: 'Up to £15,000; around 21 grants.', decision_timeline: 'Deadline 27 November 2026; decisions by the end of January 2027.',
      how_to_apply: 'Through Historic England\'s grants pages.' }) },
  { title: 'Natural Resources Wales Peatland Restoration Grant 2027', funder: 'Natural Resources Wales', funder_type: 'government', funding_type: 'grant', funding_subtypes: ['capital'],
    apply_url: 'https://naturalresources.wales/about-us/grants-and-funding/peatland-restoration-grant/?lang=en', url_status: 'unchecked', location_tag: 'Wales', is_local: false,
    amount_min: 10000, amount_max: 250000, deadline: '2026-11-30', is_rolling: false, eligible_structures: ALL,
    impact_sectors: ['environment'], target_beneficiaries: ['general_public'],
    description: 'Grants of £10,000 to £250,000 from Natural Resources Wales, funded at 100 per cent of eligible costs through the Welsh Government\'s National Peatland Action Programme, for the development or delivery of peatland restoration projects in Wales that bring climate, nature, carbon storage and flood resilience benefits. Open to private landowners and public or voluntary organisations, including charities and third sector bodies, with confirmed technical support from a partner or contractor experienced in peatland restoration. Deadline 30 November 2026 for delivery in the 2027/28 year.',
    funder_brief: D({ is_local: false, location_tag: 'Wales',
      who_can_apply: 'Individuals and private landowners, public sector organisations, registered charities, universities, third sector and private sector organisations, with confirmed technical support from an experienced restoration partner.',
      typical_award: '£10,000 to £250,000 at 100 per cent of eligible costs.', decision_timeline: 'Deadline 30 November 2026.',
      how_to_apply: 'Through the Natural Resources Wales grants pages; a reference number is needed to start an application.',
      _citations: { who_can_apply: c('individuals, public sector organisations, registered charities, universities and research institutes, third sector organisations, and private sector organisations', 'https://www.iucn-uk-peatlandprogramme.org/news/natural-resources-wales-announces-new-funding-peatland-restoration', 'med') } }) },
]

async function main() {
  const db = getAdminDb()
  console.log(APPLY ? 'APPLY' : 'DRY RUN', '| rows in list', NEW.length)
  type Held = { id: string; title: string; pipeline_state: string; apply_url: string | null }
  const all: Held[] = []
  for (let from = 0; ; from += 1000) {
    const { data, error } = await db.from('scraped_grants').select('id, title, pipeline_state, apply_url').range(from, from + 999)
    if (error) throw error
    all.push(...(data as Held[])); if (!data || data.length < 1000) break
  }
  const { count } = await db.from('scraped_grants').select('id', { count: 'exact', head: true })
  console.log(`table read: ${all.length} rows (table has ${count})`)
  if (all.length !== count) throw new Error('partial read; refusing to dedup against part of the table')
  const norm = (u: string) => u.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '')
  let staged = 0, skipped = 0
  for (const row of NEW) {
    const exact = all.filter(d => d.apply_url && norm(d.apply_url) === norm(row.apply_url))
    if (exact.length) { skipped++; console.log(`  already_held, skipping: ${row.title} -> ${exact.map(d => `${d.title} [${d.pipeline_state}]`).join('; ')}`); continue }
    const sameTitle = all.filter(d => d.title.toLowerCase().startsWith(row.title.toLowerCase().slice(0, 40)) && !['rejected', 'archived'].includes(d.pipeline_state))
    if (sameTitle.length) { skipped++; console.log(`  similar title held, skipping: ${row.title} -> ${sameTitle.map(d => `${d.title} [${d.pipeline_state}]`).join('; ')}`); continue }
    console.log(`  stage ${row.title}`)
    if (!APPLY) continue
    const stamped = { ...stampNewGrant({ ...row, source: SRC, is_active: false }, SRC), pipeline_state: 'tagged_awaiting_review' }
    const { data, error } = await db.from('scraped_grants').insert(stamped).select('id').single()
    if (error) throw error
    console.log('     inserted', data.id); staged++
  }
  console.log(`\n${APPLY ? 'staged' : 'would stage'} ${APPLY ? staged : NEW.length - skipped}, skipped ${skipped}`)
}
main().catch(e => { console.error(e); process.exit(1) })
